### ISSUE TITLE
Simulated imagery data module

### ISSUE THREAD

**Issue by claretandy** [MetOffice/forest#174]
A while ago FOREST displayed simulated imagery from the regional and global models, alongside satellite imagery. This dropped off the list of datasets that we display at some point, so this ticket is to reinstate it.

**Comment by andrewgryan** [comment]
Excellent, this can be best tackled a la **rdt.py**, with a `View`/`Loader` pair in `simim.py`. A `Locator` could be a good idea too. It might be worth thinking about re-usable `Locator`s since there will be lots of overlap with the Locator in **rdt.py**

**Comment by andrewgryan** [comment]
How similar is `simim` data to gridded forecast data, could this be addressed by #148?

**Comment by claretandy** [comment]
Maybe, but thinking about it, the simim data is actually just another model variable. However, not all of the timesteps from a run are processed so it wouldn't match the timeseteps of the other model fields. So actually the issue is to decide whether (1) we want to gracefully handle the missing model data (can a dataset have fields with different time steps?), or whether (2) we want to display the simim field as a separate dataset. My preference would be (1).

**Comment by claretandy** [comment]
So, in the yaml file, can we point a dataset at multiple input files? To me that would be the simplest solution.

**Comment by andrewgryan** [comment]
In the yaml file there is only support for a single `pattern` and `directory` associated with each "group" of data. As a work around

```yaml
files:
    - label: GA6
      pattern: 'umglaa*'
      directory: '/some/um/dir'
      file_type: gridded_forecast
  - label: GA6-Simim
      pattern: 'simim*.nc'
      directory: '/some/simim/dir'
      file_type: gridded_forecast
```

**Comment by andrewgryan** [comment]
A more elegant approach would allow multiple sources to be used by the same label. The above approach exposes the storage decisions to the user. This would then involve making a `Locator` that can find data from multiple glob patterns.

```yaml
files:
  - label: GA6
    locator:
      kind: file_system
      options:
      - pattern: "umglaa*"
        directory: "/some/um/dir"
        file_type: gridded_forecast
      - pattern: "simim*.nc"
        directory: "/some/simim/dir"
        file_type: gridded_forecast
```
Would we need multiple locators for a single group, e.g. `HTTP`, `SQL` and `FileSystem` could be sources of information for various parameters inside a single "group", e.g. Global operational UM forecasts
