### ISSUE TITLE
Formalise loader/view relationship and API

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#186]
Use a `drivers` directory and a formal consistent API across all "file_types"

- Document how to write a driver for a new data set
- Relax dimensionality concerns (maybe separate issue)

**Comment by andrewgryan** [comment]
- `Navigator.dimensions -> []str`
- `Navigator.points(dimension, **kwargs) -> []interface{}`

**Comment by andrewgryan** [comment]
- `Loader.image(state) -> {x: ..., y: ..., dw: ..., etc.}` needed by `view.UMView`

**Comment by andrewgryan** [comment]
`State`, it's usage and future vision for what it encapsulates is covered in #176

**Comment by andrewgryan** [comment]
- File system specific details should not appear in constructor of `navigate.Config`, since we now support web based catalogues

**Comment by andrewgryan** [comment]
Change `--file-type` to `--driver` and corresponding config item. The intention is to use `import forest.drivers.<name>` to load the driver at run time needed to access the data

**Comment by andrewgryan** [comment]
Or even, `driver = forest.drivers.load(driver_name)` as a convenience function that `main.py` can call, we can sanitize the keywords and protect against import injection there

**Comment by rhattersley** [comment]
> I put the factory method in as a convenience for testing, constructing a `Dataset` should not require parsing a `Config`

Agreed. Configuration construction (either from a file or from command line arguments) should be a separate activity. But the dataset will need the configuration when it's constructed, i.e.:

```python
configs = ... # Get configuration from file and/or command line
for config in configs:
    driver = forest.drivers.load(config.driver_name)
    dataset = driver.Dataset(config)
```

**Comment by andrewgryan** [comment]
What would be a good way to represent this in the config.yaml file?

Simply rename `file_type` to `driver`?
```yaml
files:
   - label: Operational suite
     driver: gridded_forecast
     pattern: *.nc
     locator: database
```

Or nest the driver specific settings?

```yaml
files:
   - label: Operational suite
     driver: gridded_forecast
     driver_settings:
         pattern: *.nc
         locator: database
   - label: CMIP6 catalogue
     driver: cmip6
     driver_settings:
         endpoint: http://cmip.endpoint/rest
```
What feels more natural?
